apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-web-app-dep
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-web-app
  template:
    metadata:
      labels:
        app: sample-web-app
    spec:
      containers:
      - name: my-sample-web-app
        image: cprimecontainer.azurecr.io/akannan1087/sample-web-app:#{Build.BuildId}#
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
# service type loadbalancer       
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: sample-web-app
    k8s-app: sample-web-app
  name: sample-web-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8085
  type: LoadBalancer
  selector:
    app: sample-web-app
