apiVersion : apps/v1
kind: Deployment
metadata:
  name: cprimedevopstask 
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cprimedevopstask
  template:
    metadata:
      labels:
        app: cprimedevopstask 
    spec:
      containers:
        - name: cprimedevopstask 
          image: myacrrepo431.azurecr.io/akannanspringbootapp
          ports:
          - containerPort: 80
